### ISSUE TITLE
Add a license to the repository

### ISSUE THREAD

**Issue by cbjuan** [contepablod/IBMQuantumChallengeFall2022#1]
I recently came across your project IBMQuantumChallengeFall2022 and I noticed that the repository github.com/contepablod/IBMQuantumChallengeFall2022 currently does not have a license specified.

Why Adding a License is Important?

As [GitHub documents](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)
>Public repositories on GitHub are often used to share open source software. For your repository to truly be open source, you'll need to license it so that others are free to use, change, and distribute the software.

Would be possible to add a valid license to this repository? Probably something really OpenSource such as the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0) would fit really well.

Thanks!

**Comment by contepablod** [comment]
Actually you can find it 'officialy' at the IBM-Quantum Repo, this is just the same added in this repo

**Comment by cbjuan** [comment]
Ok, thank you!

**Comment by contepablod** [comment]
If you are interested I wrote an article on LinkedIn time ago about the IBM Challenge and the chemical reaction challenge. Hope you find it enjoyable. 

https://www.linkedin.com/pulse/ibm-quantum-challenge-fall-2022-pablo-conte/

Best!

**Comment by cbjuan** [comment]
Thanks for the link! 👀
